name: olmo_doc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py311h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cairo=1.16.0=he5ede1b_6
  - comm=0.2.1=py311h06a4308_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - icu=73.1=h6a678d5_0
  - ipykernel=6.29.5=py311h06a4308_1
  - ipython=9.1.0=py311h06a4308_0
  - ipython_pygments_lexers=1.1.1=py311h06a4308_0
  - jedi=0.19.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.1=h7b32b05_0
  - packaging=24.2=py311h06a4308_0
  - parso=0.8.4=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py311h06a4308_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.7=py311h06a4308_0
  - poppler=24.09.0=hc52b300_2
  - poppler-data=0.4.11=h06a4308_1
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py311h06a4308_0
  - python=3.11.13=h1a3bd86_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - pyzmq=26.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - six=1.17.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - anyascii==0.3.3
      - anyio==4.9.0
      - beaker-py==2.4.4
      - bleach==6.2.0
      - boto3==1.39.1
      - botocore==1.39.1
      - cached-path==1.7.3
      - cachetools==5.5.2
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - cryptography==45.0.5
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - doctr==1.9.0
      - filelock==3.18.0
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-cloud-core==2.4.3
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.2
      - idna==3.10
      - img2pdf==0.6.1
      - jinja2==3.1.6
      - jmespath==1.0.1
      - langdetect==1.0.9
      - lingua-language-detector==2.1.1
      - lxml==6.0.0
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - olmocr==0.1.76
      - opencv-python==4.11.0.86
      - orjson==3.10.18
      - pikepdf==9.9.0
      - pillow==11.3.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyclipper==1.3.0.post6
      - pycparser==2.22
      - pypdf==5.7.0
      - pypdf2==3.0.1
      - pypdfium2==4.30.1
      - python-doctr==0.12.0
      - pyyaml==6.0.2
      - rapidfuzz==3.13.0
      - regex==2024.11.6
      - requests==2.32.4
      - rich==13.9.4
      - rsa==4.9.1
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scipy==1.16.0
      - shapely==2.1.1
      - smart-open==7.3.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.53.0
      - triton==3.3.1
      - urllib3==2.5.0
      - validators==0.35.0
      - webencodings==0.5.1
      - wrapt==1.17.2
      - zstandard==0.23.0
prefix: /home/cristobal/miniconda3/envs/olmo_doc
